apiVersion: v1
kind: Namespace
metadata:
  name: androidworld
  labels:
    name: androidworld
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: androidworld-staging
  labels:
    name: androidworld-staging
    environment: staging
